### PR TITLE
Misc and man

### PR DESCRIPTION
**Pull request by stek29**

### CODE REVIEW

**Comment by LubosD** [comment]
Ideally, you should always submit a second PR for updating the submodule commit in darlinghq/darling.

**Comment by stek29** [comment]
@LubosD I thought I should _not_ do that, but I will from now on.

But I'm not sure if this tools should be even compiled and installed, since Darling has/will have xcrun shims for them. Maybe they should be installed to some alternative path which would be then added to Darling's xcselect?

**Comment by LubosD** [comment]
@stek29 You are right - I was thinking the same, but I didn't want to discourage you with such complexities ;-)

**Comment by stek29** [comment]
@LubosD I think I'd just change install path to [`/usr/libexec/DeveloperTools`](https://github.com/darlinghq/darling/blob/master/src/xcselect/xcselect.c#L257).

**Pull request merged**
